### ISSUE TITLE
Trace output

### ISSUE THREAD

**Issue by melardev** [blechschmidt/massdns#110]
Hi, I have a situation where I want to get the intermediate/trace output, is it possible?
The thing is, I have the following chain when making an NS query:

HostName -- 1 NS Record --> 3party DNS Server -- 2 NS Records --> Somes Hosts

The way to read the above "flow" is:
The hostname is managed by the registrar panel, there we added an NS record, pointing to a 3-party DNS solution, that 3-party DNS solution has a zone file(which we own) and that zone file has  2 NS records for the hostname.

The thing is, the registrar always returns a value for NS query, it returns "3party DNS server".
If the whole chain is set up and working, the query proceeds further and hits the 3party DNS Server which in turn returns the 2 NS records in the response, however,
if the chain is broken, because for example, the 3party DNS Server is down or decommissioned, the 3party DNS Server of course returns an error, but prior to that, looking at the trace, obviously, the registrar's DNS did return a value for the NS query for the hostname, is there a way to get that value?

My intention is to always get the NS record response from the registrar of hostname, I don't want it to reach 3-party DNS server, if it does it is not a problem, but at least, when the chain is broken I don't want to receive an error, instead, I want to receive the NS response from the registrar, I have looked at what arguments are available and it does not seem possible.

If I did not explain well, here it is a similar, yet not exact situation, dig returns error without `+trace` however, it succeeds with it.
That's more or less my problem, when the chain is healthy I get something, if not I get an error, but I want to get the intermediate response massdns already got.

**Comment by blechschmidt** [comment]
MassDNS is a stub resolver, which means it does not support iterative queries, i.e. it only contacts the resolvers specified in the resolvers file. Thus, it does not support tracing.
