### ISSUE TITLE
Simple list output please :)

### ISSUE THREAD

**Issue by gprime31** [blechschmidt/massdns#112]
Simple list like:
example.com
example.ca
example.in
exams.co
etc...
simple list format for use with httprobe and amass
Thanks :)

**Comment by blechschmidt** [comment]
I agree that such an output mode is probably required in many use-cases, which is why 0ce8f4baf4ada03e2cfb59e50fcedacf45754b4f adds it. In particular, when the reliability of resolvers is high (e.g. when probing authoritative nameservers directly), it may be quite useful.
