### ISSUE TITLE
Dns resolvers

### ISSUE THREAD

**Issue by wicked-wick** [blechschmidt/massdns#119]
Hey, i want to confirm if i should use resolvers provided by the tool i.e default or setup resolvers from somewhere else..?

**Comment by blechschmidt** [comment]
No, they are outdated and I am hesitating to update them as I fear that the list might quickly degenerate when being used by all massdns users. It is better to maintain your own list (or maybe use the resolvers from https://public-dns.info/nameservers.txt, which are updated regularly).

In case you are performing subdomain enumeration, there might be no need for external resolvers. Consider probing against the authoritative nameservers directly.
