### ISSUE TITLE
error when installing on win10

### ISSUE THREAD

**Issue by hilaryrottinghausqdd44** [blechschmidt/massdns#123]
![image](https://user-images.githubusercontent.com/88131391/149351567-5e190ebb-d794-49c6-845a-fa30bd3f96fe.png)

**Comment by br0k3NaN** [comment]
![image](https://user-images.githubusercontent.com/3386569/149377704-5fcc9897-9c93-47af-9208-06511938dd32.png)

Same issue on macOS. Any thoughts?

**Comment by br0k3NaN** [comment]
![image](https://user-images.githubusercontent.com/3386569/149381225-2b31e5bf-91f0-434a-af5c-68ca48010943.png)
Same problem in macOS. Any thoughts?
Thanks

**Comment by jhhd88** [comment]
> ![image](https://user-images.githubusercontent.com/88131391/149351567-5e190ebb-d794-49c6-845a-fa30bd3f96fe.png)

+1

**Comment by br0k3NaN** [comment]
The solution I found it's using homebrew -  `brew install massdns`.
Thanks 👍
