### ISSUE TITLE
Problem compiling on macOS

### ISSUE THREAD

**Issue by infosec-it-init** [blechschmidt/massdns#127]
On macOS there is an error compiling using `make nolinux`:
```
src/main.c:504:54: error: use of undeclared identifier 'IPV6_HDRINCL'
        if(setsockopt(info.descriptor, IPPROTO_IPV6, IPV6_HDRINCL, &enable, sizeof(enable)) < 0)
```

**Comment by blechschmidt** [comment]
This has been fixed by a5a17668c05b2485e9e1b25abf4d2eb0f7a773c0. It should compile now. However, on systems where `IPV6_HDRINCL` is not present, `--rand-src-ipv6` will not be available.
