### ISSUE TITLE
massdns install problem on windows

### ISSUE THREAD

**Issue by joyahamad074** [blechschmidt/massdns#129]
Hi,
I try install massdns on windows but it didn't install. I install cygwin and all the package which required for massdns.
But when I use "make" command it shows me the error like this:
`mkdir -p bin
cc    -DMASSDNS_REVISION=\"v1.0.0-62-g2c3e399+\" -O3 -std=c11 -DHAVE_EPOLL -DHAVE_SYSINFO -Wall -fstack-protector-strong src/main.c -o bin/massdns
In file included from src/main.c:9:
src/massdns.h:10:14: fatal error: sys/epoll.h: No such file or directory
   10 |     #include <sys/epoll.h>
      |              ^~~~~~~~~~~~~
compilation terminated.
make: *** [Makefile:6: all] Error 1
`

**Comment by blechschmidt** [comment]
On Windows, massdns needs to be built using `make nolinux`.

**Comment by AliYar-Khan** [comment]
gives this error when `make nolinux` is used

```
mkdir -p bin
cc    -DMASSDNS_REVISION=\"v1.0.0-86-g6586950\" -O3 -std=c11 -Wall -fstack-protector-strong src/main.c -o bin/massdns
process_begin: CreateProcess(NULL, cc -DMASSDNS_REVISION=\"v1.0.0-86-g6586950\" -O3 -std=c11 -Wall -fstack-protector-strong src/main.c -o bin/massdns, ...) failed.
make (e=2): The system cannot find the file specified.
make: *** [Makefile:12: nolinux] Error 2
```
