### ISSUE TITLE
output data is unrecognize

### ISSUE THREAD

**Issue by ev01ing** [blechschmidt/massdns#130]
{"name":"lbpb.com.","type":"AAAA","class":"IN","status":"NOERROR","data":{"answers":[{"ttl":3600,"type":"AAAA","class":"IN","name":"lbpb.com.","data":"\\x12\\xa6\\xf8\\xd0"}]},"resolver":"223.5.5.2:53"}

data is like above. the data is not an ipv6. I don't know what is "\\x12\\xa6\\xf8\\xd0".

this is manay data like this.

{"name":"67tc.com.","type":"AAAA","class":"IN","status":"NOERROR","data":{"answers":[{"ttl":3600,"type":"AAAA","class":"IN","name":"67tc.com.","data":"\\x12\\xa6\\xf8\\xd0"}]},"resolver":"60.191.134.206:53"}
{"name":"wwwhg222.com.","type":"AAAA","class":"IN","status":"NOERROR","data":{"answers":[{"ttl":3600,"type":"AAAA","class":"IN","name":"wwwhg222.com.","data":"\\x12\\xa6\\xf8\\xd0"}]},"resolver":"202.98.192.67:53"}
{"name":"65382.com.","type":"AAAA","class":"IN","status":"NOERROR","data":{"answers":[{"ttl":3600,"type":"AAAA","class":"IN","name":"65382.com.","data":"\\x12\\xa6\\xf8\\xd0"}]},"resolver":"4.2.2.2:53"}
{"name":"bwkl.com.","type":"AAAA","class":"IN","status":"NOERROR","data":{"answers":[{"ttl":3600,"type":"AAAA","class":"IN","name":"bwkl.com.","data":"\\x12\\xa6\\xf8\\xd0"}]},"resolver":"202.98.224.70:53"}
{"name":"a1838.com.","type":"AAAA","class":"IN","status":"NOERROR","data":{"answers":[{"ttl":3600,"type":"AAAA","class":"IN","name":"a1838.com.","data":"\\x12\\xa6\\xf8\\xd0"}]},"resolver":"202.98.226.70:53"}

**Comment by blechschmidt** [comment]
For some reason, the reply packets from these domains are malformed. They only return four bytes of data for an IPv6 address. MassDNS is working correctly in this case and simply outputs the raw data. You can confirm this using `dig @4.2.2.2 AAAA 67tc.com.`, which reports a warning: `Message parser reports malformed message packet.` All domains share the nameservers `hkd001.ddddns.net.` and `hkd002.ddddns.net.`, so it is likely a nameserver implementation issue.

![malformed](https://user-images.githubusercontent.com/18330291/184346737-fb8e5ac7-bf05-4617-938f-e30d9d4c888a.png)
