### ISSUE TITLE
Meaning of --verify-ip flag

### ISSUE THREAD

**Issue by msasad** [blechschmidt/massdns#150]
Can someone with certain knowledge please explain What does this flag do? I tried to search on the Internet but couldn't find any good answers.

**Comment by blechschmidt** [comment]
By default, massdns will not verify incoming IP addresses. This option enables source IP verification of incoming
packets. That is, it only accepts replies from the resolver addresses specified in the resolvers file.

For example, if you send DNS requests to 1.1.1.1, massdns would by default accept answers from 8.8.8.8. With this option, it no longer does.

**Comment by msasad** [comment]
Thanks
