### ISSUE TITLE
Unable to compile massdns on Ubuntu(linux)

### ISSUE THREAD

**Issue by marvelmaniac** [blechschmidt/massdns#152]
I am getting this error when I run make inside the massdns directory - 

```
root@localhost:/trash/massdns# make V=1
mkdir -p bin
cc    -DMASSDNS_REVISION=\"v1.1.0-7-gbad45b8\" -O3 -std=c11 -DHAVE_EPOLL -DHAVE_SYSINFO -Wall -fstack-protector-strong src/main.c -o bin/massdns
make: cc: No such file or directory
make: *** [Makefile:6: all] Error 127
```
![Screenshot 2024-03-31 224811](https://github.com/blechschmidt/massdns/assets/83338418/2584babc-02dd-4714-ada8-5c0c1f8c2c68)

Make version - `GNU Make 4.3`

**Comment by blechschmidt** [comment]
You probably need to install the `build-essential` package through `apt install build-essential`.

**Comment by marvelmaniac** [comment]
Gotcha. Thanks! It works now.
