### ISSUE TITLE
No buffer space available Error

### ISSUE THREAD

**Issue by phith0n** [blechschmidt/massdns#17]
When I ran massdns in mac OSX EI Capitan, I got the error:

```
Failed to adjust socket send buffer size.: No buffer space available
Failed to adjust socket receive buffer size.: No buffer space available
```

How to solve it?

**Comment by blechschmidt** [comment]
You can use the newly implemented `--sndbuf` and `--rcvbuf` arguments now to adjust the buffer sizes. Set them to `0` in order to not change the default buffer size.
