### ISSUE TITLE
error on make

### ISSUE THREAD

**Issue by c0ldb00t3r** [blechschmidt/massdns#18]
![massdns](https://user-images.githubusercontent.com/10518727/28539635-091c33fa-70d0-11e7-949b-4c4540a62554.jpg)

i am not able to install

**Comment by blechschmidt** [comment]
I cannot reproduce this error. Making worked for me on a Kali 2016.1 VM.
What version of Kali are you using?
Did you install `libldns-dev`?

**Comment by c0ldb00t3r** [comment]
![image](https://user-images.githubusercontent.com/10518727/28605508-eb25392a-71ef-11e7-9a2d-cbb3392e8cd0.png)
on vm

**Comment by blechschmidt** [comment]
Could you please post the output of `dpkg -s libldns-dev`?

**Comment by c0ldb00t3r** [comment]
extremely sorry for raising issue .the problem was with my vbox network issue. That's why it was showing installed. Forgive me for wasting your time
