### ISSUE TITLE
The send buffer size has to be a valid number larger than or equal to 0.

### ISSUE THREAD

**Issue by jhaddix** [blechschmidt/massdns#19]
Hey @blechschmidt ,

Thanks for the wonderful tool! and thank you for including a reference to my subdomain list. 

I was running a demo last night and ran across this error:

"The send buffer size has to be a valid number larger than or equal to 0."

Any ideas?

**Comment by blechschmidt** [comment]
Hi,

thank you for the nice presentation at LevelUp and the subdomain list.
The issue you were experiencing should have been fixed by 20e3eba.
