### ISSUE TITLE
Feature request: time left

### ISSUE THREAD

**Issue by avlidienbrunn** [blechschmidt/massdns#2]
Would be nice to have an estimated time left (should be fairly easy since average/second and total is already tracked).

**Comment by blechschmidt** [comment]
Thank you for the suggestion. It has been implemented by 7c9439a8119af4ba1df379a4a6ed19f722672484.
However, you are required to manually specify the `--progress` option as it requires pre-counting the elements within the domain list (which may take some time if you are e.g. huge lists of domains).
