### ISSUE TITLE
Centos 7 Issue

### ISSUE THREAD

**Issue by Rhynorater** [blechschmidt/massdns#21]
~~~~
[root@rhynorater massdns]# make
mkdir -p bin
cc  -std=c11 -Wall -fstack-protector-strong *.c -o bin/massdns -lldns -ldl
main.c: In function 'record_from_str':
main.c:129:16: error: 'LDNS_RR_TYPE_CAA' undeclared (first use in this function)
         return LDNS_RR_TYPE_CAA;
                ^
main.c:129:16: note: each undeclared identifier is reported only once for each function it appears in
make: *** [all] Error 1
~~~~

This is the error I get when I am trying to compile on Centos 7. I have LDNS installed. Any suggestions?

**Comment by blechschmidt** [comment]
It looks like the `ldns-devel` package on CentOS is outdated and lacks the `LDNS_RR_TYPE_CAA` declaration. Instead, remove the `ldns-devel` package, download ldns from https://www.nlnetlabs.nl/projects/ldns/, extract it and build it from source using `./configure --disable-dane-ta-usage; make install`. (This requires `openssl-devel` to be installed.) Finally, you should be able to build massdns.

**Comment by Rhynorater** [comment]
I can confirm that this has fixed the issue.
