### ISSUE TITLE
Getting broke pipe error

### ISSUE THREAD

**Issue by infosecsecurity** [blechschmidt/massdns#26]
![screenshot from 2018-03-28 20-43-54](https://user-images.githubusercontent.com/7826342/38062156-cc8654e6-32c8-11e8-9b33-fe0a6a625cd7.png)

**Comment by blechschmidt** [comment]
The command line parameters have changed and therefore several tutorials have become outdated. The `-a` parameter is not understood by the new CLI and gets interpreted as domain file.

Using the most recent version, you likely want to pipe to `./bin/massdns -r lists/resolvers.txt -t A -o S -w results.txt`. Please have a look at the [readme file](https://github.com/blechschmidt/massdns/blob/master/README.md).

I also highly recommend to not use the `--root` parameter.

**Comment by infosecsecurity** [comment]
Thank you very much
