### ISSUE TITLE
#define ⇒ enum?

### ISSUE THREAD

**Issue by elfring** [blechschmidt/massdns#3]
Would you like to replace more defines for constant values by [enumerations](https://en.wikipedia.org/wiki/Enumerated_type#C_and_syntactically_similar_languages) to stress their relationships?
* [DNS_RECORD_…](https://github.com/blechschmidt/massdns/blob/0758e16a5883f52dddf8383ec8838cf471ea6a3a/dns.h#L26)
* [DNS_REPLY_…](https://github.com/blechschmidt/massdns/blob/0758e16a5883f52dddf8383ec8838cf471ea6a3a/dns.h#L59)

**Comment by blechschmidt** [comment]
This issue should be obsolete with the introduction of ldns.
