### ISSUE TITLE
MassDNS Outputs To Many False Positives

### ISSUE THREAD

**Issue by alisalmanbilal** [blechschmidt/massdns#34]
Upon trying to use massdns with the inbuilt subbrut.py module the resulting output contains to many false positives the command which I used was ./scripts/subbrute.py /root/all.txt TARGET.com | ./bin/massdns -r lists/resolvers.txt -t A -o S -w OUTPUT.txt and the wordlist I used was all.txt by Jason Haddix the time taken for MassDNS to complete was 3 minutes 01 seconds, I'm using MassDNS on 16.04 on a Digital Ocean Droplet (Singapore Server), any idea how I could fix this?

**Comment by blechschmidt** [comment]
The default resolver list is known to contain a lot of unusable resolvers.

Please have a look at issue https://github.com/blechschmidt/massdns/issues/22.
Consider using the text lists from https://public-dns.info/ instead or setting up your own resolver.
