### ISSUE TITLE
MassDNS overload Question

### ISSUE THREAD

**Issue by oldesec** [blechschmidt/massdns#41]
Hello,

I have a question.

Where does the massdns tool overload it?

Target site?

Or ISP DNS server?

Thanks.

**Comment by rremo** [comment]
> Please note that the usage of MassDNS may cause a significant load on the **used resolvers** and _result_ in _abuse_ complaints being _sent to your ISP_.

**Comment by manikandanbaskarans** [comment]
i want know about the resolve.txt  in the massdns comments how can i get the file ? if any body know pls reply.

**Comment by blechschmidt** [comment]
MassDNS queries the DNS resolvers supplied via `-r`. They may in turn contact the authoriative name servers for the queried DNS names. The `resolvers.txt` file is found in the `lists` folder.
