### ISSUE TITLE
only NXDOMAIN scan??

### ISSUE THREAD

**Issue by Phoenix1112** [blechschmidt/massdns#46]
hello . thanks for this program... With massdns i just want to get nxdomain results? What command should I run to find nxdomain subdomain names?

**Comment by mansoorr123** [comment]
Although above problem can be solved by :
./massdns -q -t A -r /opt/resolvers.txt domain_list.txt -o F -w output_massdns.txt
cat output_massdns.txt | grep NXDOMAIN -A 7 | grep CNAME
But it is not efficient.

**Comment by blechschmidt** [comment]
The `ndjson` output format now allows to easily scan for `NXDOMAIN` results. The `status` field can be used for filtering.

Example output (pretty-printed):
```
{
   "name":"doesnotexist-lalala.com.",
   "type":"A",
   "class":"IN",
   "status":"NXDOMAIN",
   "data":{
      "authorities":[
         {
            "ttl":899,
            "type":"SOA",
            "class":"IN",
            "name":"com.",
            "data":"a.gtld-servers.net. nstld.verisign-grs.com. 1584909553 1800 900 604800 86400"
         }
      ]
   },
   "resolver":"8.8.8.8:53"
}
```
