### ISSUE TITLE
Data from /dev/urandom is overwritten by rand()

### ISSUE THREAD

**Issue by avlidienbrunn** [blechschmidt/massdns#5]
The commit https://github.com/blechschmidt/massdns/commit/8df0535154d67f21626c039f7e43666965aef758 contains a fix that writes lookup->transaction with data from /dev/urandom.

If reading from /dev/urandom succeeds, the line after overwrites lookup->transaction with data from rand(). I'm guessing this is not intended and you want to remove that line (https://github.com/blechschmidt/massdns/blob/master/main.c#L566)

**Comment by blechschmidt** [comment]
Thank you for reporting this issue. It has been fixed by 08998829c3eb7e699546248765728f2b1513ac10.
Most of the issues should be fixed as soon as the use of libldns has been implemented.
