### ISSUE TITLE
Stucks when file is empty.

### ISSUE THREAD

**Issue by karasamil** [blechschmidt/massdns#50]
When given domain file is empty, the program stucks and doesnt exit.

My command: `massdns -r /tools/massdns/lists/resolvers.txt hosts.txt`

`wc hosts.txt` result: `0 0 0 hosts.txt`

**Comment by faizal3199** [comment]
Also, if the input file contains only newlines.

**Comment by blechschmidt** [comment]
Thank you for reporting This should have been fixed by ef081dad04a14700e21e47d161dd61afcc04f6d9.
