### ISSUE TITLE
Add resolver to output

### ISSUE THREAD

**Issue by meme-lord** [blechschmidt/massdns#52]
It would be useful to get the resolver that returned the response in the output.
Makes it easier to remove resolvers that are returning bogus responses.

**Comment by blechschmidt** [comment]
There is an `r` flag for the simple mode to prepend resolver IP address, Unix timestamp and return code to the question line.

**Comment by rkreddypandu** [comment]
@blechschmidt , With the "r" flag, massdns is not giving any output. The sample command I used is ",assdns -r resolvers.txt -t A domains.txt -o Sr"
