### ISSUE TITLE
Real-time stderr update as single JSON line rather than free text lines w/ANSI escape ccodes?

### ISSUE THREAD

**Issue by mzpqnxow** [blechschmidt/massdns#58]
It would be useful in some cases to monitor the status of massdns in real-time programmatically. Currently, the only good way to do this is with regular expressions, and this can be painful and expensive because of the ansi escape codes and the cost of executing regex compares

Would you accept a PR that adds a flag for the status output to be a single line of JSON?

**Comment by mzpqnxow** [comment]
I opened PR #59 in case this is an acceptable feature. It is pretty non-invasive and does not change the default behavior.

Note #59 also has an update for the README

**Comment by blechschmidt** [comment]
Thank you very much for contributing. The PR has been merged.
