### ISSUE TITLE
 False  Positives  and A error of  " . " 

### ISSUE THREAD

**Issue by darkmachineweb** [blechschmidt/massdns#65]
my file contains 3 sub domains
```
mail.ru
health.mail.ru
aldfkadsflkadsfjklads.mail.ru
```
i used 
```
cat file | massdns -r resolv.txt -t A -w hahah -o S
```
i got
```
health.mail.ru. A 94.100.180.243
health.mail.ru. A 94.100.180.242
aldfkadsflkadsfjklads.mail.ru. A 94.100.180.87
aldfkadsflkadsfjklads.mail.ru. A 217.69.139.87
mail.ru. A 217.69.139.200
mail.ru. A 94.100.180.201
mail.ru. A 94.100.180.200
mail.ru. A 217.69.139.202
```
did u find two error ?
first error:
each subdomain has a . at last , see carefully
secondly it gives ip of a non existent domain. 
Any help here?

**Comment by darkmachineweb** [comment]
Non existent subdomain is aldfkjadsklfjldskfjsdl.mail.ru.

**Comment by bauthard** [comment]
```
$ host aldfkjadsklfjldskfjsdl.mail.ru
aldfkjadsklfjldskfjsdl.mail.ru has address 94.100.180.87
aldfkjadsklfjldskfjsdl.mail.ru has address 217.69.139.87
```

@darkmachineweb it has valid A record, and it's a wildcard, so massdns is doing what is expected from it i.e resolving subdomains with a valid record, you need to handle wildcard on your side.

**Comment by blechschmidt** [comment]
The dot at the end is also desired behavior. See http://www.dns-sd.org/trailingdotsindomainnames.html.

**Comment by darkmachineweb** [comment]
how to end this behaviour in MASSDNS
