### ISSUE TITLE
Publish image in Docker Hub

### ISSUE THREAD

**Issue by Maks3w** [blechschmidt/massdns#71]
I suggest automatic deployment of the Dockerfile in Docker Hub.

This is a more easier way of start to use the tool without to clone the repo and perform manual steps.

Integration in Docker Hub is as faster as link both repos so Docker Hub starts to build new images as branch pushes occurs

https://docs.docker.com/docker-hub/builds/

**Comment by blechschmidt** [comment]
These images are now available at https://hub.docker.com/r/blechschmidt/massdns, i.e. they can be referred to by `blechschmidt/massdns:latest`.
