### ISSUE TITLE
Inability to output result in a file

### ISSUE THREAD

**Issue by Doktatech** [blechschmidt/massdns#75]
When i run _massdns -r ~/massdns/lists/resolvers.txt -t A -o S -w massdns.txt alldomains.txt_ on small list of subdomains, the resolving works fine and i get my output as needed. However, when i run same cmd using commonspeak2-wordlists(~500,000) the result does not ouput to the file? The ouput on terminal is normal but after finishing nothing ouputs to the file. Mark you, some of the inputs from alldomains.txt resolve well when run in a small list of themselves?

**Comment by blechschmidt** [comment]
Sounds to me like the `-s` parameter is too large in your case. Begin with a small value (maybe 10) and gradually increase it if it works. Secondly, I do not recommend using the included resolver list because it is outdated.
