### ISSUE TITLE
Add a status output interval option🙏

### ISSUE THREAD

**Issue by shmilylty** [blechschmidt/massdns#80]
Massdns status output is very useful, but when using other program calls, the massdns status output interval is very short, there will be a lot of information output, which will pollute the original software log output. I very much hope that massdns will add a status output interval option, and then the defauult time can be set to 1 second. Thank you very much.😊

**Comment by blechschmidt** [comment]
The status output already occurs once per second. In your case, you should probably parse the stderr output of massdns (with `--status-format json`) and output it at will.
