### ISSUE TITLE
Dockerfile deleted

### ISSUE THREAD

**Issue by phackt** [blechschmidt/massdns#84]
Hello, may you let us know why the Dockerfile has been deleted (not maintained anymore ?), there is no comment for this commit:
https://github.com/blechschmidt/massdns/commit/ed1f257130ffbbde260661b169fbd0d6fbe1f578

What is the way to build massdns container ? I mean will an official image be provided for massdns on docker hub or anything else ?

Thanks a lot,

**Comment by blechschmidt** [comment]
Hi,

I wanted to switch to Alpine and remove the dependencies that are not needed anymore but forgot to commit the new Dockerfile.

7c4e30c7fe996c03117a53c2a1a0679e5cbe26de adds the file. I still need some time to look into Docker Hub (#71).

**Comment by phackt** [comment]
What efficiency ! Thanks a lot @blechschmidt 
Cheers.
