### ISSUE TITLE
Problem with JSON format on -oJ. Can't process it with jq

### ISSUE THREAD

**Issue by Cloufish** [blechschmidt/massdns#88]
Hey,
When trying to parse the json format with ```jq``` i get
```bash
> cat masscan_grepable.json | jq    
parse error: Expected another array element at line 3, column 1
```
I'm not that familiar with JSON format, but I've checked in with [JSON Validator](https://jsonlint.com/?code=) And I got:

![image](https://user-images.githubusercontent.com/32965886/100436181-4e81e100-309f-11eb-9996-b6c1ed9ea404.png)

It looks like there's a unnecessary comma at the end of an array of objects (don't know the exact terminology) on line 11

**Comment by blechschmidt** [comment]
This is not massdns output. You might be confusing massdns with [masscan](https://github.com/robertdavidgraham/masscan).

**Comment by Cloufish** [comment]
God I'm sorry XD
