### ISSUE TITLE
mass dns  not installing on centos 

### ISSUE THREAD

**Issue by ap062** [blechschmidt/massdns#90]
mkdir -p bin
cc  -O3 -std=c11 -DHAVE_EPOLL -DHAVE_SYSINFO -Wall -fstack-protector-strong src/main.c -o bin/massdns
make: cc: Command not found
make: *** [all] Error 127
![image](https://user-images.githubusercontent.com/64496315/102007019-733ab180-3d4b-11eb-839a-6134da08cfcd.png)

**Comment by blechschmidt** [comment]
Looks like the C compiler is missing. Does `sudo yum groupinstall 'Development Tools'` help?
