### ISSUE TITLE
-t A options resolves with CNAME

### ISSUE THREAD

**Issue by storenth** [blechschmidt/massdns#92]
Now I am using `massdns` to explicitly get only A records:
```bash
massdns -r $resolvers -t A -o S -w ./output.txt ./subdomains.txt
```
But I got output with CNAMEs too:
```bash
# output.txt
0-honeybee.k8s-exp.shopifykloud.com. A 193.58.251.1
_config_.web.mdm.global.druid.shopifykloud.com. CNAME FimglNohlfcjecje._config_.web.mdm.global.druid.shopifykloud.com.
```

**Comment by blechschmidt** [comment]
This is desired behavior as massdns just outputs the raw DNS responses. However, CNAME flattening would be a nice optional feature.

I am closing this as it is the same request as in issue #1.

**Comment by youradds** [comment]
Was there ever a way around this? I'm using:

`$massdns_folder/bin/massdns -q -r $massdns_folder/lists/resolvers.txt -o S -t A $massdns_folder/domains-to-do.txt -w $massdns_folder/results.txt`

And this correctly gets the A records, but also the CNAME records. What I'm having to do, is add in another step in my Perl script, which finds those CNAME values, and then grabs the A records for the CNAME value:

`			if ($type eq "A") {

				if (!$seen->{$domain}) {
					$seen->{$domain} = $ip;
				} else {
					$seen->{$domain} .= " $ip";
				}
			} elsif ($type eq "CNAME") {

				$ip =~ s/\.$//; # get rid of trailing . on CNAME value

				print qq|GOT CNAME: $ip - trying to get IPS for $domain now...\n|;

				#dig a685977b5a52b19b6dff-5a9cb61253446dd190fe5cfd42b4418e.r6.cf1.rackcdn.com +short | paste -d " " - - -
				#GOT CNAME: nnnxip.ccc26.biz - trying to get IPS now...
        		#GOT: nnnxip.ccc26.biz. lcyl011.gotzvip.com. ww.gotzvip.com. gfccc36.nuinui-301.com. gfccc36.g59p.com. 172.247.193.116 192.151.192.166

				# seems to be pointing somewhere else, so lets try and get the IPs form the CNAME destination
				my $test = `dig $domain +short | paste -d " " - - -`;
				   $test =~ s/\n/ /g;
				   $test =~ s/\s+$//g; # get rid of trailing spaces

				if ($test) {

					my @tmp_ips;
					foreach (split / /, $test) {
						if (/\d+\.\d+\.\d+\.\d+/) {
							# valid ip...
							push @tmp_ips, $_;
						}
					}
					my $ips_grabbed	= join (" ", @tmp_ips);
					print qq|\tGOT: $ips_grabbed \n|;
					$seen->{$domain} = $ips_grabbed;
				}

			}`

Its a bit messy and slow, so if there is a better way to do it I'd appreciate a pointer #6 

Thanks

Andy
