### ISSUE TITLE
Can you brute subdomain in batches?

### ISSUE THREAD

**Issue by Xia0Ny1** [blechschmidt/massdns#93]

**Comment by blechschmidt** [comment]
I am not sure whether I understand that question correctly, but massdns gets a list of DNS names as input and resolves those. It currently does perform hierarchical subdomain enumeration on its own (i.e. automatically enumerating subdomains of `sub.example.com` after having identified `sub` as a subdomain of `example.com`). However, it should not be hard to leverage massdns to perform this kind of task by creating some wrapper script.
