### ISSUE TITLE
GPL-3.0 license is deprecated

### ISSUE THREAD

**Issue by chenrui333** [blechschmidt/massdns#94]
👋  It looks like the repo still using GPL-3.0 license, but it is deprecated in favor of `GPL-3.0-only` or `GPL-3.0-or-later`. Thanks!

**Comment by blechschmidt** [comment]
Hi,

I have added SPDX license identifiers to all source files (224ac5546fa1d2e9956561ee8b6bd517fa8136d9). As the code was published under the GPLv3 and no CLA has been signed by contributors, the license of this project is `GPL-3.0-only`.

Furthermore, I have released version 1.0.0 which includes some bug fixes compared to the previously released version.

**Comment by chenrui333** [comment]
Nice!! Gonna update my formula this. Thanks a lot!
