### ISSUE TITLE
can't compile/install on kali linux

### ISSUE THREAD

**Issue by radwan2017** [blechschmidt/massdns#95]
when i run the command make i see this error 

mkdir -p bin
cc  -O3 -std=c11 -DHAVE_EPOLL -DHAVE_SYSINFO -Wall -fstack-protector-strong src/main.c -o bin/massdns
In file included from src/massdns.h:6,
                 from src/main.c:9:
/usr/lib/gcc/x86_64-linux-gnu/10/include/stdint.h:9:16: fatal error: stdint.h: No such file or directory
    9 | # include_next <stdint.h>
      |                ^~~~~~~~~~
compilation terminated.
make: *** [Makefile:5: all] Error 1

what should i do?

**Comment by blechschmidt** [comment]
Did you install the `build-essential` package? (`apt install build-essential`)
